name: MechanicalTools
description: Adds Mechanical Tools and Blocks to Bukkit Servers
main: com.mechanicals.plugin.MechMain
author: IballisticBoss
version: 2.4.1
commands:
  mechanical:
    description: Shows help on commands for this plugin.
    usage: /mechanical [blocks/items]
  mechanicalconfig:
    description: Allows you to adjust the configuration of the plugin.
    usage: /mechanicalconfig <view/set/confirm/reset> [...]
  remotemechanicalinventory:
    description: Allows you to view and ajust another player's remote inventory
    usage: /remotemechanicalinventory <player>
  rmi:
    description: Allows you to view and ajust another player's remote inventory
    usage: /rmi <player>
  blockplacer:
    description: Give a Block Placer tool to a player/yourself.
    usage: /blockplacer (target)
  blockbreaker:
    description: Give a Block Breaker tool to a player/yourself.
    usage: /blockbreaker (target)
  treecutter:
    description: Give a Tree Cutter tool to a player/yourself.
    usage: /treecutter (target)
  entityteleporter:
    description: Give an Entity Teleporter tool to a player/yourself.
    usage: /entityteleporter (target)
  itemteleporter:
    description: Give an Item Teleporter tool to a player/yourself.
    usage: /itemteleporter (target)
  grinder:
    description: Give an Grinder tool to a player/yourself.
    usage: /grinder (target)
  largeteleporter:
    description: Give a Large Teleporter tool to a player/yourself.
    usage: /largeteleporter (target)
  chunkloader:
    description: Give a Chunk Loader tool to a player/yourself.
    usage: /chunkloader (target)
  elevator:
    description: Give a Elevator tool to a player/yourself.
    usage: /elevator (target)
  animalgrowth:
    description: Give an Animal Growth tool to a player/yourself.
    usage: /animalgrowth (target)
  plantfarmer:
    description: Give an Plant Farmer tool to a player/yourself.
    usage: /plantfarmer (target)
  spawnpointteleporter:
    description: Give an Spawn Point Teleporter tool to a player/yourself.
    usage: /spawnpointteleporter (target)
  mechradio:
    description: Give a Radio item to a player/yourself.
    usage: /mechradio (target)
  itool:
    description: Give an ITool item to a player/yourself.
    usage: /itool (target)
  dyewand:
    description: Give a DyeWand item to a player/yourself.
    usage: /dyewand (target)
  flamethrower:
    description: Give a Flamethrower item to a player/yourself.
    usage: /flamethrower (target)
  schemnow:
    description: Schematics
    usage: /schemnow <name> <x1> <y1> <z1> <x2> <y2> <z2>

softdepend: [NoteBlockAPI, WorldEdit, Vault]
